name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec637d050be58f057b695b68b7b91d9405b11772ef9c62e63009d466ad5ba799"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
