name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "deabd9c39eec5e9a6bd213e0bed3c1e23838f92836cbd55f7b3aebdfa43b3e5d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
