name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "340a6f60d5fec521e06e5a3f56f62324fb99bc1ea20961e62ad5db906a9af413"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
