name = "ModFest 1.21"
author = "ModFest"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78ca878489aed12916b2375e48fd38e72447ba824ee8b42aff5fe1011c6c68a3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
