name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b46aa806990068457dc3c0ed48e8c0b322bfdb366809a833f3cba279e893d1dd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
