name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc4ec9a4279d906988c60498c9bcb36d07d11e9cd4359a83935726857bbba1b9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
