name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f434c4faefdafc3d9d44e4005834d5828a20298f385c28ca5ae2b76ef5084f4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
