name = "ModFest 1.21"
author = "ModFest"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3dc6f3a62b3c46b54a7931161e4dec933c5ff5526188e471c4d4d1dd65f64983"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
