name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf6e164f653b52197ca300d79ebc8c3dee8c264936a271e6964828d0bb20792e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
