name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0de7eaa0dc074cce0097ac3cacbf021c76f5351cc1150c9f54aef797875bdc25"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
