name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9af303615219f7b1ae7a52e12fbc30809d3a31379886ec72f43d464371bd75a4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
