name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c32747def0695592b679614dc1b386202524355273da88fd89adaa34dded791d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
