name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "961c0131b084ec76debd69441b3d0c3d3debf228ccc1a60440d77b203d1f989f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
