name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ff89b010507edd87017db3c22b51de67e495430bef1636096c7ed387cb6f5e7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
