name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b72868d34b2dc093d26a0f6cef5de2ee724c6b97260b413101ab2a5e1229a44"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
