name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e170496c51fe98818db58e3310ba09bc40efaa2c579faee609e2f0688b39d61"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
