name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ab2d592e653acb7d497d4c48b680b89a45b7d77fec3aa9752ecfe9dcde6c098"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
