name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "337ec169157cd5ed0163c214d2941f3e5c76cf5e1ad8b4050f08f5be56b649ed"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
