name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26e3371c2f5d6337c0c9881559ff0ea12f744da6cb75af78ed2f80a863d6d262"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
