name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98d2b57ec8c345e1e8b75a5981ecbb32c63a9ebfdf12204798ec5c1a6f710fde"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
