name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "827c6756ecbfb9d90f50298baa9463b8044f1e40073088bc89cb22e35c8248f2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
